### ISSUE TITLE
Optimize sheet todo list

### ISSUE THREAD

**Issue by Monolith11** [Monolith11/memo#98]
- [ ] Adventurer Magician #69 
- [x] Bow Master #115 
- [x] Pathfinder #8 #59 
- [x] Evan
- [x] Mercedes #43
- [x] Xenon
- [x] Demon Slayer #94
- [ ] Cadena #51
- [ ] Kain #123 #127 #128 #129
- [x] Angelic Buster #55 
- [ ] Zero #113 
- [x] Hoyoung #93 #92
- [x] Add new familiar badge (tenebris)
- [x] Optimize Familiar Badge
- [x] Optimize link skill (cadena, kms zero)
- [x] Add Ursus Avatar
- [x] Keydown skill minimum prepare.time = 60 #131
- [ ] Keydown skill minimum prepare.time = 60 for main attack skills #142
